#ifndef CSTRUCT_TYPES_H
#define CSTRUCT_TYPES_H

enum CStructType {
    NONE = 0,
    INTEGER,
    FLOAT,
    STRING,
    LOCAL_STRING,
    PAIR,
    VECTOR,
    SCRIPT,
    C_FUNCTION,
    MEMBER_FUNCTION,
    STRUCTURE,
    STRUCTURE_POINTER,
    ARRAY,
    NAME,
    BYTE,
    SHORT,
    UNSIGNED_BYTE,
    UNSIGNED_SHORT,
    ZERO_INTEGER,
    ZERO_FLOAT,
    STRUCTURE_REFERENCE,
    ARRAY_REFERENCE,
    STATIC_FAST_STRUCTURE,
    DYNAMIC_FAST_STRUCTURE,
    FLAG,
    TEMPLATE
};

#endif //CSTRUCT_TYPES_H
